FROM jrei/systemd-ubuntu

RUN apt-get update
RUN apt-get -y install bash iproute2 net-tools tcpdump vim iputils-ping

RUN apt-get -y install python3-pip
RUN apt-get -y install telnet
RUN pip3 install pexpect --break-system-packages

COPY ./frrsetup /root
RUN /root/frrsetup
COPY ./daemons /etc/frr/daemons
COPY ./r2_frr.conf /etc/frr/frr.conf
COPY ./ospfraise /root
COPY ./ospflower /root

CMD ["bash"]
